version: '3.7'

services:
  elephone-management:
    image: elephone-management:latest
    container_name: elephone-management
    ports:
      - 8080:8080
    environment:
      AWS_ACCESS_KEY_ID: AKIAY2SZAZO3CMM25PLT
      AWS_SECRET_ACCESS_KEY: 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
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_8ovxzl36v
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
    networks:
      - elephone-network

  postgres:
    image: postgres:12.2-alpine
    container_name: elephone-management-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - elephone-management-postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elephone-network

networks:
  elephone-network:
    driver: bridge

volumes:
  elephone-management-postgres-data:


