version: '3.7'

services:
  elephone-management:
    image: elephone-management
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: elephone-management
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - elephone-network

  postgres:
    image: postgres:12.2-alpine
    container_name: elephone-management-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - elephone-management-postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elephone-network

networks:
  elephone-network:
    driver: bridge

volumes:
  elephone-management-postgres-data:


