version: '3.7'

services:
  elephone-management:
    image: elephone-management:latest
    container_name: elephone-management
    ports:
      - 8080:8080
    args:
      AWS_REGION: ap-southeast-2
      AWS_DB_URL: jdbc:postgresql://localhost:5432/elephone
      AWS_USERPOOL_ID: ap-southeast-2_8ovxzl36v
      AWS_COGNITO_URL: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_8ovxzl36v
      AWS_ACCESS_KEY_ID: AKIAY2SZAZO3CMM25PLT
      AWS_SECRET_ACCESS_KEY: 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
    environment:
      SPRING_ACTIVE_PROFILE: docker
      SPRING_DATASOURCE_USERNAME: elephone
      SPRING_DATASOURCE_PASSWORD: elephone
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8080/actuator/health 2>&1 | grep UP || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - elephone-network

  postgres:
    image: postgres:12.2
    container_name: elephone-management-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: elephone
      POSTGRES_USER: elephone
      POSTGRES_PASSWORD: elephone
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elephone-network

networks:
  elephone-network:
    driver: bridge

volumes:
  elephone-management-postgres-data:
    driver: local


