info:
  app:
    name: Elephone Management
    version: 1.0.0


spring:
  application:
    name: management
  main:
    banner-mode: off
  datasource:
    platform: postgres
    url: jdbc-secretsmanager:postgresql://${AWS_DB_URL}?stringtype=unspecified
    username: ${AWS_SECRET}
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    database: postgresql
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_8ovxzl36v
  jackson:
    time-zone: Australia/Sydney

cloud:
  aws:
    cognito:
      userpoolId: ap-southeast-2_8ovxzl36v
    credentials:
      accessKey: AKIAY2SZAZO3CMM25PLT
      secretKey: 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
      region: ap-southeast-2




