info:
  app:
    name: Elephone Management
    version: 1.0.0


spring:
  application:
    name: management
  main:
    banner-mode: off
  datasource:
    platform: postgres
    url: jdbc-secretsmanager:postgresql://${AWS_DB_URL}?stringtype=unspecified
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: ${AWS_SECRET}
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/${AWS_COGNITO_USERPOOLID}
  jackson:
    time-zone: Australia/Sydney

aws:
  cognito:
    userpoolId: ${AWS_COGNITO_USERPOOLID}

ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 30
    keep-alive-duration: 300

vend:
  url: https://elephone.vendhq.com/api/2.0

oss:
  enable: true
  info: true
  path-style-access: true
  region: ap-southeast-2
  endpoint: s3-ap-southeast-2.amazonaws.com
  access-key: AKIAY2SZAZO3LKWTVNPV
  secret-key: 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
  bucket-name: elephone-server