info:
  app:
    name: Elephone Management
    version: 1.0.0


spring:
  application:
    name: management
  main:
    banner-mode: off
  datasource:
    platform: postgres
    url: jdbc-secretsmanager:postgresql://${AWS_DB_URL}?stringtype=unspecified
    username: ${AWS_SECRET}
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    database: postgresql
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/${AWS_USERPOOL_ID}
  jackson:
    time-zone: "Australia/Sydney"

cloud:
  aws:
    cognito:
      userpoolId: ${AWS_USERPOOL_ID}
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
      region: ${AWS_REGION}




