info:
  app:
    name: Elephone Management
    version: 1.0.0

spring:
  application:
    name: management
  datasource:
    platform: postgres
    url: jdbc-secretsmanager:postgresql://elephone-management.cluster-cwj4a30evopq.ap-southeast-2.rds.amazonaws.com:5432/elephone
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: elephone-management
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_DXhjoJV7e

cloud:
  aws:
    cognito:
      userpoolId: ap-southeast-2_DXhjoJV7e
    credentials:
      accessKey: AKIAY2SZAZO3EOIDMVT5
      secretKey: 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




