spring:
  datasource:
    url: jdbc:postgresql://elephone-management.cluster-cwj4a30evopq.ap-southeast-2.rds.amazonaws.com:5432/elephone
    username: elephone
    password: elephone
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_DXhjoJV7e