info:
  app:
    name: Elephone Management
    version: 1.0.0

spring:
  application:
    name: management
  datasource:
    platform: postgres
    url: ${AWS_DB_URL:}
    username: postgres
    password: postgres
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    database: postgresql
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/${AWS_USERPOOL_ID:ap-southeast-2_8ovxzl36v}

cloud:
  aws:
    cognito:
      userpoolId: ${AWS_USERPOOL_ID:ap-southeast-2_8ovxzl36v}
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:}
      secretKey: ${AWS_SECRET_ACCESS_KEY:}
      region: ${AWS_REGION:}




