spring:
  datasource:
    url: ${AWS_DB_URL:jdbc:postgresql://localhost:5432/elephone}
    username: elephone
    password: elephone
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AWS_OAUTH_SERVER:}